from typing import Protocol

from salocore.models import Round, Team, Tournament


class NotificationServiceProtocol(Protocol):
    def reg_start(self, tournament: Tournament) -> None: ...

    def reg_end(self, tournament: Tournament) -> None: ...

    def finish_tournament(self, tournament: Tournament) -> None: ...

    def start_round(self, round: Round) -> None: ...

    def close_submissions(self, round: Round) -> None: ...

    def finish_evaluation(self, round: Round) -> None: ...

    def team_invite(self, team: Team, target_user_id: int) -> None: ...

    def jury_invite(self, tournament: Tournament, target_user_id: int) -> None: ...

    def admin_invite(self, tournament: Tournament, target_user_id: int) -> None: ...

    def kicked_from_team(self, team: Team, target_user_id: int) -> None: ...
