services:
  redis:
    image: redis:7-alpine
    container_name: saloboard_redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:16-alpine
    container_name: saloboard_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-saloboard}
      - POSTGRES_USER=${POSTGRES_USER:-salouser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-salopass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always

  web:
    build: .
    container_name: saloboard_web
    ports:
      - "8888:8000"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://${POSTGRES_USER:-salouser}:${POSTGRES_PASSWORD:-salopass}@db:5435/${POSTGRES_DB:-saloboard}
      - IS_DEV_DATABASE=False
    depends_on:
      - redis
      - db
    restart: always

  celery_worker:
    build: .
    container_name: saloboard_worker
    command: celery -A saloboard worker -l info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://${POSTGRES_USER:-salouser}:${POSTGRES_PASSWORD:-salopass}@db:5432/${POSTGRES_DB:-saloboard}
      - IS_DEV_DATABASE=False
    depends_on:
      - redis
      - db
    restart: always

  celery_beat:
    build: .
    container_name: saloboard_beat
    command: celery -A saloboard beat -l info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://${POSTGRES_USER:-salouser}:${POSTGRES_PASSWORD:-salopass}@db:5432/${POSTGRES_DB:-saloboard}
      - IS_DEV_DATABASE=False
    depends_on:
      - redis
      - db
    restart: always

volumes:
  postgres_data:
