# Generated by Django 6.0.2 on 2026-04-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salocore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ended_at',
            field=models.DateTimeField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
