# Generated by Django 6.0.2 on 2026-05-05 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salocore', '0002_alter_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='max_score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('JI', 'Jury Invite'), ('TI', 'Team Invite'), ('AI', 'Admin Invite'), ('KT', 'Kicked from Team'), ('KJ', 'Kicked from Jury'), ('KA', 'Kicked from Admin'), ('TRS', 'Tournament reg start'), ('TRE', 'Tournament reg end'), ('TF', 'Tournament finished'), ('RS', 'Round started'), ('SD', 'Submission Deadline Soon'), ('SF', 'Submission finished'), ('EF', 'Evaluation Finished')], max_length=20),
        ),
    ]
