# Generated by Django 6.0.2 on 2026-05-12 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salocore', '0003_alter_evaluationcriterion_max_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='orderIndex',
            new_name='order_index',
        ),
    ]
